version: '3'
services:
  postgres:
    container_name: dvdrental-db
    build: ./image/postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  dbt:
    container_name: dbt
    build: ./image/dbt
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./src/:/usr/app/dbt
      - ./profiles/:/root/.dbt
